# Generated by Django 4.1.3 on 2023-01-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=50)),
                ("customer_mobile", models.CharField(max_length=50)),
                ("customer_address", models.TextField()),
            ],
            options={
                "verbose_name_plural": "2. Customers",
            },
        ),
        migrations.CreateModel(
            name="ItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("detail", models.TextField()),
            ],
            options={
                "verbose_name_plural": "7. Items Detail",
            },
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_list",
                    models.CharField(
                        choices=[("مفرد", "مفرد"), ("جملة", "جملة"), ("شراء", "شراء")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("item_price", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemdetail",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6. Item Price",
            },
        ),
        migrations.CreateModel(
            name="Payment_terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_terms_type", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.SlugField(default=0)),
            ],
            options={
                "verbose_name_plural": "8. Purchase Invoice",
            },
        ),
        migrations.CreateModel(
            name="SaleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.SlugField(default=0)),
                (
                    "customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.customer",
                    ),
                ),
                (
                    "payment_terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.payment_terms",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Sale Invoice",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "5. Units",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("mobile", models.CharField(max_length=15)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "1. Vendors",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField()),
                ("price", models.FloatField()),
                ("total_amt", models.FloatField()),
                ("pur_date", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemdetail",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="electro.vendor"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "8. Stock",
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField()),
                ("total_amt", models.FloatField(default=0, editable=False)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemdetail",
                    ),
                ),
                (
                    "item_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemprice",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.saleinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "9. Sales Item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField()),
                ("total_amt", models.FloatField(default=0, editable=False)),
                ("pur_date", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemdetail",
                    ),
                ),
                (
                    "item_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemprice",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "9. Purchased Item",
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="electro.vendor"
            ),
        ),
        migrations.AddField(
            model_name="itemdetail",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="electro.unit"
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pur_qty", models.FloatField(default=0, null=True)),
                ("sale_qty", models.FloatField(default=0, null=True)),
                ("total_bal_qty", models.FloatField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.itemdetail",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.purchase",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.saleinvoice",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.stock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "10. Stock Details",
            },
        ),
    ]
